baseurl = "http://nyakokishi.github.io/"
languageCode = "zh-cn"
title = "喵爵"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"


[[menu.main]]
    name = "编程"
    url = "/categories/编程"
    weight = 4

[[menu.main]]
    name = "数学"
    url = "/categories/数学"
    weight = 5

[[menu.main]]
    name = "乱扯一通"
    url = "/categories/乱扯一通"
    weight = 6
[[menu.main]]
    name = "关于"
    url = "/about"
    weight = 7



[params]
    description = ""
    subtitle = "啊咧？！我滴timeline？(ʘ̆ʚʘ̆)"
    title = "在下喵爵"
    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
