baseurl = "http://nyakokishi.github.io/"
languageCode = "zh-cn"
title = "nyakokishi's blog"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 7



[params]
    description = ""
    subtitle = "猥琐扭曲卡哇伊"
    title = "nyakokishi"
    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
